---
title: "Bayesian Mixed-Effects Models for Film Festival"
author: "Jadyn Park"
date: "2025-03-10"
output: 
  html_document: 
    code_folding: hide
    fig_width: 4
    fig_height: 4
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, fig.show=FALSE)
knitr::opts_knit$set(root.dir = getwd()) 

# Clear environment
rm(list = ls())

# Load libraries
library(dplyr); library(brms); library(rstan); library(ggplot2); library(posterior); library(distributional); library(tidybayes); library(brms); library(bayestestR)

# Help stan run faster
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

# Set directory
dir = "../projects/"

# Import Film Festival data
path_ff = paste0(dir, "filmfestival/data/1_fmri/R/filmfest_allData.csv")
df_filmfest <- read.csv(path_ff, header=TRUE)

# Change subject and events to factors
df_filmfest$subj <- as.factor(df_filmfest$subj)
df_filmfest$events <- as.factor(df_filmfest$events)

```

```{r fxs}

# ----------------------------- Define functions ----------------------------- #

zscore <- function(x) {(x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)}

sem <- function(x) {sd(x,na.rm = T) / sqrt(length(x))}

detach_package <- function(pkg, character.only = FALSE)
{
  if(!character.only)
  {
    pkg <- deparse(substitute(pkg))
  }
  search_item <- paste("package", pkg, sep = ":")
  while(search_item %in% search())
  {
    detach(search_item, unload = TRUE, character.only = TRUE)
  }
}
```

```{r}

# Subset df
df_filmfest_subset <- df_filmfest %>%
  dplyr::select(arousal_llm, recall_fidelity, contains("movie"))

# Z-score all columns
df_ff <- as.data.frame(apply(df_filmfest_subset, 2, scale))
df_ff$subj <- df_filmfest$subj
df_ff$events <- df_filmfest$events
df_ff$recall <- df_filmfest$recall

```


### Model1: Recall fidelity predicted by average PC 

```{r}

df <- df_ff %>% dplyr::select(subj, events, recall_fidelity, PC_movie_avg)

# Linear model: recall_fidelity ~ PC_movie_avg + (1+PC_movie_avg | subj)

# Define priors
prior1.1 <- c(
  prior(normal(0, 5), class = Intercept),
  prior(normal(0, 5), class = b, coef = PC_movie_avg), # Prior for slope at population-level
  prior(cauchy(0, 2), class = sd), # Prior for random effects
  prior(cauchy(0, 2), class = sigma), # Prior for sigma at population-level
  prior(lkj(2), class = cor)
)

model1.1 <- brm(
  recall_fidelity ~ PC_movie_avg + (1 + PC_movie_avg | subj),
  data = df,
  prior = prior1.1,
  control = list(adapt_delta = 0.95),
  chains = 4, cores = 4, iter = 4000, warmup = 1000, seed = 123)

# Posterior distribution of model 1.1
posterior1.1 <- as_draws_df(model1.1)$b_PC_movie_avg

# Summary of posterior
posterior1.1_hdi <- hdi(posterior1.1, ci=0.95, method = "HDI")
posterior1.1_hdi

# Prop. posterior < 0 and > 0
below_zero <- sum(posterior1.1 < 0)/length(posterior1.1)
above_zero <- sum(posterior1.1 > 0)/length(posterior1.1)

a <- summary(model1.1)
summary_model1.1 <- rbind(data.frame(a$fixed), data.frame(a$spec_pars) )
rownames(summary_model1.1) <- c("$\\alpha$", "$\\beta$", "$\\sigma_{e}$")
colnames(summary_model1.1) <- c("mean","SE", "lower bound", "upper bound", "Rhat", "ESS_bulk", "ESS_tail")

summary_model1.1 %<>%
    dplyr::select(-ESS_bulk, -ESS_tail) %>% # removing ESS
    rownames_to_column(var = "parameter")

summary_model1.1

# ---------------------------Histogram Plot --------------------------------- #

model1.1_hist <- ggplot(data.frame(posterior1.1), aes(x=posterior1.1)) +
  geom_histogram(fill="lightblue") +
  labs(x="Posterior distribution") +
  geom_vline(xintercept=0, colour="azure4", linetype=2) +
  scale_color_manual(values = "black") +
  theme_classic()   +
  theme(
    legend.position="none",
    text=element_text(size=22, family="Arial", color="black"),
    axis.title=element_text(size=22, color="black"),
    axis.text.x=element_text(size=22, color="black"),
    axis.text.y=element_blank(),
    axis.title.y=element_blank(),
    plot.margin=margin(0, 1, 0, 1, "cm")
  ) +
  # Add HDI
  geom_errorbarh(aes(y=0, x=posterior1.1_hdi$CI_low, xmin=posterior1.1_hdi$CI_low, xmax=posterior1.1_hdi$CI_high), col="black", size=2) +
  geom_text(aes(x=posterior1.1_hdi$CI_low, y=1, label=round(posterior1.1_hdi$CI_low,3)), vjust=-0.5, color="black", size=7) +
  geom_text(aes(x=posterior1.1_hdi$CI_high, y=1, label=round(posterior1.1_hdi$CI_high,3)), vjust=-0.5, color="black", size=7) +
  geom_text(aes(x=mean(posterior1.1), y=5, label=paste0("Mean=", round(mean(posterior1.1),3))), vjust=-8.5, color="black", size=7) +
  # Add prop. posterior
  geom_text(aes(x=mean(posterior1.1), y=1, label=paste0("P(posterior > 0)=", round(above_zero, 3))),
            vjust=-7.0, color="black", size=7, fontface="italic") +
  scale_x_continuous(breaks = seq(0, 0.2, by = 0.1))
model1.1_hist

```

### Model 2: Recall fidelity predicted by arousal

```{r}

df <- df_ff %>% dplyr::select(subj, events, recall_fidelity, arousal_llm)

# Linear model: recall_fidelity ~ arousal_llm + (1+arousal_llm | subj)

# Define priors
prior2.1 <- c(
  prior(normal(0, 5), class = Intercept),
  prior(normal(0, 5), class = b, coef = arousal_llm), # Prior for slope at population-level
  prior(cauchy(0, 2), class = sd), # Prior for random effects
  prior(cauchy(0, 2), class = sigma), # Prior for sigma at population-level
  prior(lkj(2), class = cor)
)

model2.1 <- brm(
  recall_fidelity ~ arousal_llm + (1 + arousal_llm | subj),
  data = df,
  prior = prior2.1,
  control = list(adapt_delta = 0.95),
  chains = 4, cores = 4, iter = 4000, warmup = 1000, seed = 123)

# Posterior distribution of model 2.1
posterior2.1 <- as_draws_df(model2.1)$b_arousal_llm

# Summary of posterior
posterior2.1_hdi <- hdi(posterior2.1, ci=0.95, method = "HDI")
posterior2.1_hdi

# Prop. posterior < 0 and > 0
below_zero <- sum(posterior2.1 < 0)/length(posterior2.1)
above_zero <- sum(posterior2.1 > 0)/length(posterior2.1)

a <- summary(model2.1)
summary_model2.1 <- rbind(data.frame(a$fixed), data.frame(a$spec_pars) )
rownames(summary_model2.1) <- c("$\\alpha$", "$\\beta$", "$\\sigma_{e}$")
colnames(summary_model2.1) <- c("mean","SE", "lower bound", "upper bound", "Rhat", "ESS_bulk", "ESS_tail")

summary_model2.1 %<>%
    dplyr::select(-ESS_bulk, -ESS_tail) %>% # removing ESS
    rownames_to_column(var = "parameter")

summary_model2.1

# ---------------------------Histogram Plot --------------------------------- #
model2.1_hist <- ggplot(data.frame(posterior2.1), aes(x=posterior2.1)) +
  geom_histogram(fill="lightblue") +
  labs(x="Posterior distribution") +
  geom_vline(xintercept=0, colour="azure4", linetype=2) +
  scale_color_manual(values = "black") +
  theme_classic()   +
  theme(
    legend.position="none",
    text=element_text(size=22, family="Arial", color="black"),
    axis.title=element_text(size=22, color="black"),
    axis.text.x=element_text(size=22, color="black"),
    axis.text.y=element_blank(),
    axis.title.y=element_blank(),
    plot.margin=margin(0, 1, 0, 1, "cm")
  ) +
  # Add HDI
  geom_errorbarh(aes(y=0, x=posterior2.1_hdi$CI_low, xmin=posterior2.1_hdi$CI_low, xmax=posterior2.1_hdi$CI_high), col="black", size=2) +
  geom_text(aes(x=posterior2.1_hdi$CI_low, y=1, label=round(posterior2.1_hdi$CI_low,3)), vjust=-0.5, color="black", size=7) +
  geom_text(aes(x=posterior2.1_hdi$CI_high, y=1, label=round(posterior2.1_hdi$CI_high,3)), vjust=-0.5, color="black", size=7) +
  geom_text(aes(x=mean(posterior2.1), y=5, label=paste0("Mean=", round(mean(posterior2.1),3))), vjust=-8.5, color="black", size=7) +
  # Add prop. posterior
  geom_text(aes(x=mean(posterior2.1), y=1, label=paste0("P(posterior > 0)=", round(above_zero, 3))),
            vjust=-7.0, color="black", size=7, fontface="italic") +
  scale_x_continuous(breaks = seq(0, 0.2, by = 0.1))

model2.1_hist

```

### Model 3: Average PC predicted by arousal

```{r}

df <- df_ff %>% dplyr::select(subj, events, PC_movie_avg, arousal_llm)

# Linear model: PC_movie_avg ~ arousal_llm + (1+arousal_llm | subj)

# Define priors
prior3.1 <- c(
  prior(normal(0, 5), class = Intercept),
  prior(normal(0, 5), class = b, coef = arousal_llm), # Prior for slope at population-level
  prior(cauchy(0, 2), class = sd), # Prior for random effects
  prior(cauchy(0, 2), class = sigma), # Prior for sigma at population-level
  prior(lkj(2), class = cor)
)

model3.1 <- brm(
  PC_movie_avg ~ arousal_llm + (1 + arousal_llm | subj),
  data = df,
  prior = prior3.1,
  control = list(adapt_delta = 0.95),
  chains = 4, cores = 4, iter = 4000, warmup = 1000, seed = 123)

# Posterior distribution of model 3.1
posterior3.1 <- as_draws_df(model3.1)$b_arousal_llm

# Summary of posterior
posterior3.1_hdi <- hdi(posterior3.1, ci=0.95, method = "HDI")
posterior3.1_hdi

# Prop. posterior < 0 and > 0
below_zero <- sum(posterior3.1 < 0)/length(posterior3.1)
above_zero <- sum(posterior3.1 > 0)/length(posterior3.1)

a <- summary(model3.1)
summary_model3.1 <- rbind(data.frame(a$fixed), data.frame(a$spec_pars) )
rownames(summary_model3.1) <- c("$\\alpha$", "$\\beta$", "$\\sigma_{e}$")
colnames(summary_model3.1) <- c("mean","SE", "lower bound", "upper bound", "Rhat", "ESS_bulk", "ESS_tail")

summary_model3.1 %<>%
    dplyr::select(-ESS_bulk, -ESS_tail) %>% # removing ESS
    rownames_to_column(var = "parameter")

summary_model3.1

# ---------------------------Histogram Plot --------------------------------- #
model3.1_hist <- ggplot(data.frame(posterior3.1), aes(x=posterior3.1)) +
  geom_histogram(fill="lightblue") +
  labs(x="Posterior distribution") +
  geom_vline(xintercept=0, colour="azure4", linetype=2) +
  scale_color_manual(values = "black") +
  theme_classic()   +
  theme(
    legend.position="none",
    text=element_text(size=22, family="Arial", color="black"),
    axis.title=element_text(size=22, color="black"),
    axis.text.x=element_text(size=22, color="black"),
    axis.text.y=element_blank(),
    axis.title.y=element_blank(),
    plot.margin=margin(0, 1, 0, 1, "cm")
  ) +
  # Add HDI
  geom_errorbarh(aes(y=0, x=posterior3.1_hdi$CI_low, xmin=posterior3.1_hdi$CI_low, xmax=posterior3.1_hdi$CI_high), col="black", size=2) +
  geom_text(aes(x=posterior3.1_hdi$CI_low, y=1, label=round(posterior3.1_hdi$CI_low,3)), vjust=-0.5, color="black", size=7) +
  geom_text(aes(x=posterior3.1_hdi$CI_high, y=1, label=round(posterior3.1_hdi$CI_high,3)), vjust=-0.5, color="black", size=7) +
  geom_text(aes(x=mean(posterior3.1), y=5, label=paste0("Mean=", round(mean(posterior3.1),3))), vjust=-8.5, color="black", size=7)  +
  # Add prop. posterior
  geom_text(aes(x=mean(posterior3.1), y=1, label=paste0("P(posterior > 0)=", round(above_zero, 3))),
            vjust=-7.0, color="black", size=7, fontface="italic") +
  scale_x_continuous(breaks = seq(0, 0.2, by = 0.1))
model3.1_hist

```

### Mediation Model 

```{r}

df <- df_ff %>% dplyr::select(subj, events,
                              recall_fidelity,
                              arousal_llm,
                              PC_movie_avg)
# Set priors
prior <- c(
  prior(normal(0, 5), class = Intercept),
  prior(normal(0, 5), class = b),
  prior(cauchy(0, 2), class = sd),
  prior(cauchy(0, 2), class = sigma),
  prior(lkj(2), class = cor)
)

# === Direct effect === #
fit_direct <- brm(recall_fidelity ~ arousal_llm + PC_movie_avg + (1 + arousal_llm | subj),
                  prior=prior,
                  control=list(adapt_delta=0.95),
                  data=df,
                  chains=4, cores=4, iter=4000, warmup=1000,
                  seed=123)
posterior_direct <- as_draws_df(fit_direct)$b_arousal_llm # Posterior distribution of the direct effect
posterior_direct_hdi <- hdi(posterior_direct, ci=0.95, method='HDI')

# === Total effect === #
fit_total <- brm(recall_fidelity ~ arousal_llm + (1 + arousal_llm | subj),
                  prior=prior,
                  control=list(adapt_delta=0.95),
                  data=df,
                  chains=4, cores=4, iter=4000, warmup=1000,
                  seed=123)
posterior_total <- as_draws_df(fit_total)$b_arousal_llm # Posterior distribution of the total effect
posterior_total_hdi <- hdi(posterior_total, ci=0.95, method='HDI')

# === Indirect effect === #
# Fit mediator model
fit_mediator <- brm(PC_movie_avg ~ arousal_llm + (1 + arousal_llm | subj),
                    prior=prior,
                    control=list(adapt_delta=0.95),
                    data=df,
                    chains=4, cores=4, iter=4000, warmup=1000,
                    seed=123)
posterior_path_a <- as_draws_df(fit_mediator)$b_arousal_llm # Posterior distribution of path a

# Fit outcome model
fit_outcome <- brm(recall_fidelity ~ arousal_llm + PC_movie_avg + (1 + arousal_llm | subj),
                   prior=prior,
                   control=list(adapt_delta=0.95),
                   data=df,
                   chains=4, cores=4, iter=4000, warmup=1000,
                   seed=123)
posterior_path_b <- as_draws_df(fit_outcome)$b_PC_movie_avg # Posterior distribution of path b (effect of PC on recall, controlling for arousal)

# Posterior distribution of indirect effect
posterior_indirect <- posterior_path_a * posterior_path_b
posterior_indirect_hdi <- hdi(posterior_indirect, ci=0.95, method='HDI')

# Summary of indirect effect
beta = mean(posterior_indirect)
above_zero_indirect = sum(posterior_indirect > 0)/length(posterior_indirect)

# Proportion mediated
prop_med <- posterior_indirect/posterior_direct
prop_med[is.nan(prop_med) | is.infinite(prop_med)] <- 0

# Summary of the proportion mediated
summary(prop_med)
prop_med_hdi <- hdi(prop_med, ci=0.95, method='HDI')

```



